services:
  auth-service:
    build:
      context: ../..
      dockerfile: ./environments/prod/Dockerfile
    image: ilikeblue/chat-app-auth-service-prod
    container_name: auth-prod
    ports:
      - "80:80"
    env_file:
      - path: ./.env
        required: true